theme: jekyll-theme-cayman
title: Welcome to UGENE's homepage!
description: UGENE is free open-source cross-platform bioinformatics software. <br/>(this is just a preliminary homepage of the project, will be updated soon)
