theme: jekyll-theme-cayman
title: Welcome to UGENE's homepage!
description: UGENE is free open-source cross-platform bioinformatics software.
show_downloads: true
github:
  zip_url: https://github.com/ugeneunipro/ugene/archive/36.0.zip
  tar_url: https://github.com/ugeneunipro/ugene/archive/36.0.tar.gz
